export const ADD_TODO = 'ADD_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';

export const ADD_SUCCESS_SNACKBAR = 'ADD_SUCCESS_SNACKBAR';
export const REMOVE_SUCCESS_SNACKBAR = 'REMOVE_SUCCESS_SNACKBAR';